services:
  # FileServer - Combined Frontend + Backend
  fileserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fileserver-app
    ports:
      - "30000:30000"   # Frontend port
      - "8443:8443"   # Backend HTTPS port
    volumes:
      # Persistent data
      - ./data:/app/data
      - ./downloads:/app/downloads
      - ./logs:/app/logs
      # Configuration files (read-only)
      - ./configs:/app/configs:ro
      - ./certs:/app/certs:ro
    environment:
      - NODE_ENV=production
      - GO_ENV=production
      - DB_PATH=/app/data/fileserver.db
      - NEXT_PUBLIC_API_URL=https://localhost:8443
      - BACKEND_URL=https://localhost:8443
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-check-certificate --quiet --tries=1 --spider https://localhost:8443/api/v1/health && wget --no-check-certificate --quiet --tries=1 --spider https://localhost:30000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fileserver-network

networks:
  fileserver-network:
    driver: bridge
